"""add multi-tenant indexes

Revision ID: 85e4b28b6c3e
Revises: 849b35abafd9
Create Date: 2026-05-23 17:40:43.157394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e4b28b6c3e'
down_revision: Union[str, None] = '849b35abafd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_data_period_id'), ['period_id'], unique=False)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('inventory_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_periods_facility_id'), ['facility_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_owner_id'))

    with op.batch_alter_table('inventory_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_periods_facility_id'))

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_org_id'))

    with op.batch_alter_table('activity_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_data_period_id'))

    # ### end Alembic commands ###
